using LoggingService.Core.Interfaces;
using LoggingService.Core.Models;

namespace LoggingService.Core.Services;

/// <summary>
/// Validates log entries for required fields and correct values.
/// </summary>
public sealed class LogEntryValidator : ILogEntryValidator
{
    private static readonly HashSet<LogLevel> ValidLogLevels =
    [
        LogLevel.Debug,
        LogLevel.Info,
        LogLevel.Warn,
        LogLevel.Error,
        LogLevel.Fatal
    ];

    /// <inheritdoc />
    public ValidationResult Validate(LogEntry entry)
    {
        var errors = new List<FieldError>();

        ValidateTimestamp(entry, errors);
        ValidateServiceId(entry, errors);
        ValidateLevel(entry, errors);
        ValidateMessage(entry, errors);
        ValidateCorrelationId(entry, errors);

        return errors.Count == 0
            ? ValidationResult.Valid()
            : ValidationResult.Invalid(errors);
    }

    private static void ValidateTimestamp(LogEntry entry, List<FieldError> errors)
    {
        if (entry.Timestamp == default)
        {
            errors.Add(new FieldError
            {
                Field = "timestamp",
                Code = "REQUIRED",
                Message = "Timestamp is required"
            });
        }
    }

    private static void ValidateServiceId(LogEntry entry, List<FieldError> errors)
    {
        if (string.IsNullOrWhiteSpace(entry.ServiceId))
        {
            errors.Add(new FieldError
            {
                Field = "serviceId",
                Code = "REQUIRED",
                Message = "ServiceId is required"
            });
        }
    }

    private static void ValidateLevel(LogEntry entry, List<FieldError> errors)
    {
        if (!ValidLogLevels.Contains(entry.Level))
        {
            errors.Add(new FieldError
            {
                Field = "level",
                Code = "INVALID",
                Message = $"Level must be one of: {string.Join(", ", ValidLogLevels)}"
            });
        }
    }

    private static void ValidateMessage(LogEntry entry, List<FieldError> errors)
    {
        if (string.IsNullOrWhiteSpace(entry.Message))
        {
            errors.Add(new FieldError
            {
                Field = "message",
                Code = "REQUIRED",
                Message = "Message is required"
            });
        }
    }

    private static void ValidateCorrelationId(LogEntry entry, List<FieldError> errors)
    {
        // CorrelationId can be empty (will be generated by enricher)
        // but if provided, it should be a valid format
        if (!string.IsNullOrEmpty(entry.CorrelationId) && !IsValidCorrelationId(entry.CorrelationId))
        {
            errors.Add(new FieldError
            {
                Field = "correlationId",
                Code = "INVALID_FORMAT",
                Message = "CorrelationId must be a valid UUID format"
            });
        }
    }

    private static bool IsValidCorrelationId(string correlationId)
    {
        return Guid.TryParse(correlationId, out _);
    }
}
