export enum ErrorCode {
  // Validation Errors (400)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_DIMENSIONS = 'INVALID_DIMENSIONS',
  INVALID_FORMAT = 'INVALID_FORMAT',
  INVALID_QUALITY = 'INVALID_QUALITY',
  INVALID_ADJUSTMENT_VALUE = 'INVALID_ADJUSTMENT_VALUE',
  INVALID_IMAGE = 'INVALID_IMAGE',
  INVALID_WATERMARK = 'INVALID_WATERMARK',
  INVALID_POSITION = 'INVALID_POSITION',
  INVALID_ANGLE = 'INVALID_ANGLE',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // Authentication Errors (401)
  MISSING_TOKEN = 'MISSING_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',

  // Authorization Errors (403)
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Not Found Errors (404)
  IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',

  // Rate Limit Errors (429)
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Server Errors (500)
  PROCESSING_ERROR = 'PROCESSING_ERROR',
  STORAGE_ERROR = 'STORAGE_ERROR',
  QUEUE_ERROR = 'QUEUE_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.INVALID_DIMENSIONS]: 400,
  [ErrorCode.INVALID_FORMAT]: 400,
  [ErrorCode.INVALID_QUALITY]: 400,
  [ErrorCode.INVALID_ADJUSTMENT_VALUE]: 400,
  [ErrorCode.INVALID_IMAGE]: 400,
  [ErrorCode.INVALID_WATERMARK]: 400,
  [ErrorCode.INVALID_POSITION]: 400,
  [ErrorCode.INVALID_ANGLE]: 400,
  [ErrorCode.MISSING_REQUIRED_FIELD]: 400,
  [ErrorCode.FILE_TOO_LARGE]: 413,
  [ErrorCode.MISSING_TOKEN]: 401,
  [ErrorCode.INVALID_TOKEN]: 401,
  [ErrorCode.EXPIRED_TOKEN]: 401,
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.IMAGE_NOT_FOUND]: 404,
  [ErrorCode.JOB_NOT_FOUND]: 404,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.PROCESSING_ERROR]: 500,
  [ErrorCode.STORAGE_ERROR]: 500,
  [ErrorCode.QUEUE_ERROR]: 500,
  [ErrorCode.INTERNAL_ERROR]: 500,
};
