<?php

declare(strict_types=1);

namespace EmailService\Tests\Property;

use EmailService\Infrastructure\Platform\LogEntry;
use EmailService\Infrastructure\Platform\LogLevel;
use Eris\Generator;
use Eris\TestTrait;
use PHPUnit\Framework\TestCase;

/**
 * Feature: email-service-modernization-2025
 * Property 5: Correlation ID Presence
 * 
 * For any log entry generated by the Email_Service, the entry SHALL contain
 * a non-empty correlation ID that follows UUID format.
 * 
 * Validates: Requirements 7.3
 */
class CorrelationIdPropertyTest extends TestCase
{
    use TestTrait;

    private const UUID_PATTERN = '/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i';

    /**
     * @test
     * Property 5: All log entries have non-empty correlation ID
     */
    public function allLogEntriesHaveNonEmptyCorrelationId(): void
    {
        $this->forAll(
            Generator\suchThat(
                fn($s) => strlen($s) >= 1 && strlen($s) <= 200,
                Generator\string()
            )
        )
        ->withMaxSize(100)
        ->then(function (string $message): void {
            $correlationId = $this->generateUuid();
            $entry = LogEntry::info($correlationId, $message);

            $this->assertNotEmpty($entry->correlationId);
            $this->assertEquals($correlationId, $entry->correlationId);
        });
    }

    /**
     * @test
     * Property 5: Correlation ID follows UUID format
     */
    public function correlationIdFollowsUuidFormat(): void
    {
        $this->forAll(
            Generator\suchThat(
                fn($s) => strlen($s) >= 1 && strlen($s) <= 100,
                Generator\string()
            )
        )
        ->withMaxSize(100)
        ->then(function (string $message): void {
            $correlationId = $this->generateUuid();
            $entry = LogEntry::info($correlationId, $message);

            $this->assertMatchesRegularExpression(
                self::UUID_PATTERN,
                $entry->correlationId,
                'Correlation ID should follow UUID format'
            );
        });
    }

    /**
     * @test
     * Property 5: Correlation ID is preserved in toArray output
     */
    public function correlationIdIsPreservedInToArrayOutput(): void
    {
        $this->forAll(
            Generator\suchThat(
                fn($s) => strlen($s) >= 1 && strlen($s) <= 100,
                Generator\string()
            )
        )
        ->withMaxSize(100)
        ->then(function (string $message): void {
            $correlationId = $this->generateUuid();
            $entry = LogEntry::info($correlationId, $message);

            $array = $entry->toArray();

            $this->assertArrayHasKey('correlation_id', $array);
            $this->assertEquals($correlationId, $array['correlation_id']);
        });
    }

    /**
     * @test
     * Property 5: All log levels include correlation ID
     */
    public function allLogLevelsIncludeCorrelationId(): void
    {
        $correlationId = $this->generateUuid();
        $message = 'Test message';

        $entries = [
            LogEntry::debug($correlationId, $message),
            LogEntry::info($correlationId, $message),
            LogEntry::warn($correlationId, $message),
            LogEntry::error($correlationId, $message),
        ];

        foreach ($entries as $entry) {
            $this->assertNotEmpty($entry->correlationId);
            $this->assertEquals($correlationId, $entry->correlationId);
        }
    }

    /**
     * @test
     * Property 5: Error log entries include correlation ID with exception
     */
    public function errorLogEntriesIncludeCorrelationIdWithException(): void
    {
        $correlationId = $this->generateUuid();
        $message = 'Error occurred';
        $exception = new \RuntimeException('Test exception');

        $entry = LogEntry::error($correlationId, $message, $exception);

        $this->assertNotEmpty($entry->correlationId);
        $this->assertEquals($correlationId, $entry->correlationId);
        $this->assertNotNull($entry->exception);

        $array = $entry->toArray();
        $this->assertArrayHasKey('correlation_id', $array);
        $this->assertArrayHasKey('exception', $array);
    }

    /**
     * @test
     * Property 5: Full LogEntry constructor preserves correlation ID
     */
    public function fullLogEntryConstructorPreservesCorrelationId(): void
    {
        $this->forAll(
            Generator\suchThat(
                fn($s) => strlen($s) >= 1 && strlen($s) <= 100,
                Generator\string()
            )
        )
        ->withMaxSize(100)
        ->then(function (string $message): void {
            $correlationId = $this->generateUuid();
            $traceId = $this->generateUuid();
            $spanId = substr($this->generateUuid(), 0, 16);

            $entry = new LogEntry(
                correlationId: $correlationId,
                serviceId: 'email-service',
                level: LogLevel::INFO,
                message: $message,
                traceId: $traceId,
                spanId: $spanId,
                userId: 'user-123',
                requestId: 'request-456',
                metadata: ['key' => 'value'],
            );

            $this->assertEquals($correlationId, $entry->correlationId);

            $array = $entry->toArray();
            $this->assertEquals($correlationId, $array['correlation_id']);
            $this->assertEquals($traceId, $array['trace_id']);
            $this->assertEquals($spanId, $array['span_id']);
        });
    }

    /**
     * @test
     * Property 5: Correlation ID is distinct from other IDs
     */
    public function correlationIdIsDistinctFromOtherIds(): void
    {
        $correlationId = $this->generateUuid();
        $traceId = $this->generateUuid();
        $requestId = $this->generateUuid();

        $entry = new LogEntry(
            correlationId: $correlationId,
            serviceId: 'email-service',
            level: LogLevel::INFO,
            message: 'Test',
            traceId: $traceId,
            requestId: $requestId,
        );

        // All IDs should be different
        $this->assertNotEquals($correlationId, $traceId);
        $this->assertNotEquals($correlationId, $requestId);
        $this->assertNotEquals($traceId, $requestId);

        // Each should be preserved correctly
        $array = $entry->toArray();
        $this->assertEquals($correlationId, $array['correlation_id']);
        $this->assertEquals($traceId, $array['trace_id']);
        $this->assertEquals($requestId, $array['request_id']);
    }

    private function generateUuid(): string
    {
        return sprintf(
            '%s-%s-%s-%s-%s',
            bin2hex(random_bytes(4)),
            bin2hex(random_bytes(2)),
            bin2hex(random_bytes(2)),
            bin2hex(random_bytes(2)),
            bin2hex(random_bytes(6))
        );
    }
}
