// Code generated by protoc-gen-go. DO NOT EDIT.
// Package proto contains the generated protobuf code for IAM Policy Service.
package proto

import (
	"context"

	"google.golang.org/grpc"
)

// IAMPolicyServiceServer is the server API for IAMPolicyService service.
type IAMPolicyServiceServer interface {
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	BatchAuthorize(context.Context, *BatchAuthorizeRequest) (*BatchAuthorizeResponse, error)
	GetUserPermissions(context.Context, *GetPermissionsRequest) (*PermissionsResponse, error)
	GetUserRoles(context.Context, *GetRolesRequest) (*RolesResponse, error)
	ReloadPolicies(context.Context, *ReloadRequest) (*ReloadResponse, error)
}

// UnimplementedIAMPolicyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIAMPolicyServiceServer struct{}

func (UnimplementedIAMPolicyServiceServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, nil
}

func (UnimplementedIAMPolicyServiceServer) BatchAuthorize(context.Context, *BatchAuthorizeRequest) (*BatchAuthorizeResponse, error) {
	return nil, nil
}

func (UnimplementedIAMPolicyServiceServer) GetUserPermissions(context.Context, *GetPermissionsRequest) (*PermissionsResponse, error) {
	return nil, nil
}

func (UnimplementedIAMPolicyServiceServer) GetUserRoles(context.Context, *GetRolesRequest) (*RolesResponse, error) {
	return nil, nil
}

func (UnimplementedIAMPolicyServiceServer) ReloadPolicies(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, nil
}

// RegisterIAMPolicyServiceServer registers the server implementation.
func RegisterIAMPolicyServiceServer(s *grpc.Server, srv IAMPolicyServiceServer) {
	s.RegisterService(&IAMPolicyService_ServiceDesc, srv)
}

// IAMPolicyService_ServiceDesc is the grpc.ServiceDesc for IAMPolicyService service.
var IAMPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.IAMPolicyService",
	HandlerType: (*IAMPolicyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "auth/iam_policy.proto",
}
