// Code generated by protoc-gen-go. DO NOT EDIT.
// Package proto contains the generated protobuf messages for IAM Policy Service.
package proto

// AuthorizeRequest represents an authorization request.
type AuthorizeRequest struct {
	SubjectId    string            `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectType  string            `protobuf:"bytes,2,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	ResourceId   string            `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType string            `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Action       string            `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Context      map[string]string `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty"`
	Environment  map[string]string `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty"`
}

// AuthorizeResponse represents an authorization response.
type AuthorizeResponse struct {
	Allowed      bool   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason       string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	PolicyId     string `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	DecisionId   string `protobuf:"bytes,4,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Signature    []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	SigningKeyId string `protobuf:"bytes,6,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
}

// BatchAuthorizeRequest represents a batch authorization request.
type BatchAuthorizeRequest struct {
	Requests []*AuthorizeRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

// BatchAuthorizeResponse represents a batch authorization response.
type BatchAuthorizeResponse struct {
	Responses []*AuthorizeResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

// GetUserPermissionsRequest represents a request to get user permissions.
type GetUserPermissionsRequest struct {
	SubjectId string   `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Roles     []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

// GetUserPermissionsResponse represents a response with user permissions.
type GetUserPermissionsResponse struct {
	Permissions []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

// GetUserRolesRequest represents a request to get user roles.
type GetUserRolesRequest struct {
	SubjectId string `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
}

// GetUserRolesResponse represents a response with user roles.
type GetUserRolesResponse struct {
	Roles []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

// ReloadPoliciesRequest represents a request to reload policies.
type ReloadPoliciesRequest struct{}

// ReloadPoliciesResponse represents a response after reloading policies.
type ReloadPoliciesResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PolicyCount  int32  `protobuf:"varint,2,opt,name=policy_count,json=policyCount,proto3" json:"policy_count,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

// GetPermissionsRequest represents a request to get permissions.
type GetPermissionsRequest struct {
	UserId string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles  []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

// PermissionsResponse represents a response with permissions.
type PermissionsResponse struct {
	Permissions []*Permission `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

// Permission represents a permission.
type Permission struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

// GetRolesRequest represents a request to get roles.
type GetRolesRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

// RolesResponse represents a response with roles.
type RolesResponse struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

// Role represents a role.
type Role struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

// ReloadRequest represents a request to reload policies.
type ReloadRequest struct{}

// ReloadResponse represents a response after reloading policies.
type ReloadResponse struct {
	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PolicyCount  int32  `protobuf:"varint,2,opt,name=policy_count,json=policyCount,proto3" json:"policy_count,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}
